package com.trickshotmlg.friendnet.core_api.proxy.payload;

public enum ProxyActionType {
    ADD_FRIEND,
    REMOVE_FRIEND,
    ACCEPT_REQUEST,
    ACCEPT_ALL_REQUESTS,
    DENY_REQUEST,
    DENY_ALL_REQUESTS,
    CANCEL_REQUEST,
    CANCEL_ALL_REQUESTS,
    BLOCK_PLAYER,
    UNBLOCK_PLAYER,
    CLEAR_BLOCKLIST,
    SET_FAVOURITE,
    SET_ALLOW_FRIEND_REQUESTS,
    SET_SHOW_ONLINE_STATUS,
    SET_AUTO_ACCEPT_FRIENDS,
    SET_FRIEND_REQUEST_NOTIFICATIONS,
    SET_FRIEND_LIST_PUBLIC,
    SET_LOCALE
}
