# Mode for the plugin: Proxy, Standalone
Mode: Standalone

# The backend to use: MySQL, SQLite, MariaDB
DatabaseType: MySQL

SupportedLocales:
  - en_US
  - de

DefaultLocale: "en_US"

# The settings for MySQL Connection
MySQL:
  host: localhost:3306
  dbName: friendnet
  username: friendnet
  password: friendnet

# The settings for SQLite Connection
SQLite:
  dbName: friendnet